apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-api
  namespace: hello-k8s
  labels:
    app: pod-info-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-info-api
  template:
    metadata:
      labels:
        app: pod-info-api
    spec:
      containers:
      - name: pod-info-api
        image: pod-info-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10 