apiVersion: v1
kind: Service
metadata:
  name: pod-info-api
  namespace: hello-k8s
  labels:
    app: pod-info-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: pod-info-api 